Algoritmo "Meu primeiro algoritmo"
// Disciplina   : [Linguagem e Logica de Programacao]
// Professor   : Gilmara Gomes Pereira Machado
// Descricaoo   : Aqui voce descreve o que o programa faz! (fun??o)
// Autor(a)    : Igor Soares Vieira Machado
// Data atual  : 09/02/2022
Var
// Secao de Declaracoes das variaveis
     nota: inteiro

Inicio
// Secao de Comandos, procedimento, funcoes, operadores, etc...
     nota <- 1000
     escreva ("Resultado:",nota)

Fimalgoritmo